### PR TITLE
Update install.php

### PR DESCRIPTION
**Pull request by ricpelo**
Fixes wrong name string for Ion Auth.

### CODE REVIEW

**Comment by kenjis** [comment]
Thank you!

**Comment by ricpelo** [comment]
You're welcome :).

**Comment by ricpelo** [comment]
One question: how can I update the install.php file in my project? Replacing it by hand is the only way?

**Comment by kenjis** [comment]
Yes.

**Comment by ricpelo** [comment]
Thank you very much :).

**Pull request merged**
